# stoxdb：专门为股票数据开发的内存型key-value数据库，一支股票一条数据。
#   key：长度不要超过64（超过64的丢弃全部数据），使用明文（非字节流），区分大小写，建议使用股票代码，例如000001.SZ
#   value：字段集合，见[field]，允许字段自定定义计算公式，见[formula]。

[server]
# 服务端配置
port              = 30634 # 监听端口
dump_file         = db.dump # 备份时写入该文件，启动时从该文件读取数据，如果文件不存在，启动时数据为空
magic_number      = 41401891 # 数据有效性检查。请使用一个小于20亿的正整数
max_recv_size     = 4194304 # 默认4M，接收数据的最大长度，超过该长度的一律丢弃
max_connections   = 32 # 最大连接数，最大支持1024个同时请求
idle_timeout      = 120  # 如果超过该时间没有请求，服务器将主动关闭该连接
transport_timeout = 30 # 数据在传输过程（发送和接收）中，如果空闲时间超出该时间，服务器将主动关闭该连接


[field]
# 一行一个字段，最多支持16000个字段
# 每个字段由3部分组成：name,type,note，数值类型字段统一默认为0
#  - name：字段名，唯一，不区分大小写（自动调整为小写），长度不大于32字节，以字母开头，后面允许数字和下划线
#  - type：字段类型
#  - note：备注，最大长度256字节

#***** 禁止操作 *****
#  - 不能删除字段
#  - 不能变动顺序
#  - 不能修改类型
# 如果做了以上操作，请重新构建数据


## type支持类型如下：
#  - int1:  1字节整数
#  - int2:  2字节整数
#  - int4:  4字节整数
#  - int8:  8字节整数，长整型
#  - int:   4字节整数
#  - float: 4字节浮点数
#  - double:8字节浮点数
#  - charN: 定长字符串，长度N，0<N<1000，存在空间浪费，不适合长文本

# name                   | type      |  note     
code                     | char12    |  股票代码 
name                     | char32    |  股票名称  
type                     | int2      |  类型
status                   | int1      |  状态      
nature                   | int1      |  公司性质，1券商 2保险 3银行 4企业 
preclose                 | float     |  昨收      
open                     | float     |  开盘价   
close                    | float     |  收盘价，当前股价
high                     | float     |  最高价   
low                      | float     |  最低价    
chg                      | float     |  涨跌额    
incr                     | float     |  涨跌幅，%
vol                      | int8      |  成交量  
amt                      | int8      |  成交额 
turnover                 | float     |  换手率，%
amp                      | float     |  振幅，%
date                     | int       |  最新交易日
time                     | int       |  行情时间
mv                       | int8      |  总市值  
mvc                      | int8      |  总流通市值
tshares                  | int8      |  总股本  
fshares                  | int8      |  总流通股本
parent_netprofit_ttm     | int8      |  归母净利润TTM
pe_ttm                   | float     |  市盈率TTM   
bonus_ttm                | int8      |  分红总金额TTM
divident_ttm             | float     |  股息率TTM   


[formula]
# 有些字段需要自动计算，请列出字段的计算公式；公式总长度不超过1024字节
# 公式仅支持简单的计算：加减乘除、小括号、求余(%)
# 公式可以包含：字段名称、操作符号、数字
# 公式以浮点数(double)进行计算，最终存储为目标类型，注意：数值较大时可能会溢出（例如，多个大数相乘，调整方式：a*b/c => a/c*b）
# 注意：如果除以0，除0结果将被强制为0，例如：a+b/0 => a+0
amp         = (high-low)/preclose*100
mv          = close * tshares
mvc         = close * fshares
PE_ttm      = mv/parent_netprofit_ttm

